### ISSUE TITLE
Details on GFN2-xtb calculation

### ISSUE THREAD

**Issue by metma99** [ghutchis/molecular-entropies#1]
Dear Geoff:
I have read your article [https://pubs.acs.org/doi/10.1021/acs.jctc.0c01213 ](url) with great interest. And thank you so much for posting the results and the scripts here.
I would like to ask you if it is possible for you to post also an example on how you ran CREST calculations.
Specifically, I would like to know how you came up with the number of conformations CREST produced in your hands.
Thank you very much in advance,
Markus

**Comment by ghutchis** [comment]
CREST output files print the number of conformations within the energy threshold (e.g., default of 6 kcal/mol). Here's an excerpt:

```
 total number unique points considered further :          13
       Erel/kcal        Etot weight/tot  conformer     set   degen     origin
       1   0.000    -7.21519    0.24512    0.98029       1       4     mtd4
       2   0.000    -7.21519    0.24511                                mtd9
       3   0.000    -7.21519    0.24511                                mtd12
       4   0.000    -7.21519    0.24495                                mtd5
       5   2.319    -7.21150    0.00491    0.01963       2       4     mtd8
       6   2.319    -7.21150    0.00491                                mtd10
       7   2.319    -7.21150    0.00491                                mtd12
       8   2.319    -7.21150    0.00491                                md6
       9   5.727    -7.20607    0.00002    0.00006       3       4     mtd9
      10   5.728    -7.20607    0.00002                                mtd4
      11   5.728    -7.20607    0.00002                                mtd13
      12   5.728    -7.20607    0.00002                                mtd2
      13   5.735    -7.20606    0.00002    0.00002       4       1     gc
T /K                                  :   298.15
E lowest                              :    -7.21519
ensemble average energy (kcal)        :    0.046
ensemble entropy (J/mol K, cal/mol K) :   12.336    2.948
ensemble free energy (kcal/mol)       :   -0.879
population of lowest in %             :   98.029
 number of unique conformers for further calc            4
```
[ZZY_2WD1_A.out.gz](https://github.com/ghutchis/molecular-entropies/files/13893831/ZZY_2WD1_A.out.gz)

The only "selection" is the energy threshold `--ewin 6`: https://crest-lab.github.io/crest-docs/page/documentation/keywords.html#ensemble-sorting-options

We simply ran CREST with the default 6 kcal/mol threshold on a pile of molecules.

**Comment by metma99** [comment]
Thank you very much
